# Generated by Django 2.1.15 on 2021-05-18 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('evenementiel', models.BooleanField(default=False)),
                ('date_evenement', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Communaute')),
            ],
            options={
                'verbose_name': 'post',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'priorite',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Priorite'),
        ),
    ]
