# Generated by Django 2.1.15 on 2021-05-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_auto_20210518_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nom',
            new_name='titre',
        ),
    ]
